name: vocabforge
services:
  vocabforge:
    build:
      context: .
    environment:
        VF_TELEGRAM_TOKEN_FILE: /run/secrets/tgtoken
        VF_OPENAI_TOKEN_FILE: /run/secrets/openaitoken
        VF_SQL_DB_PATH: /var/opt/vocabforge-data/docker_db.sqlite3
    volumes:
      - "${XDG_RUNTIME_DIR}/vf_tg_bot_token:/run/secrets/tgtoken"
      - "${XDG_RUNTIME_DIR}/vf_openai_token:/run/secrets/openaitoken"
      - ".temp/:/var/opt/vocabforge-data/"

