// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: jobs_queue.sql

package sqlc

import (
	"context"
	"time"
)

const createJob = `-- name: CreateJob :exec
INSERT INTO jobs_queue (group_name, item, created_at) VALUES (?, ?, ?)
`

type CreateJobParams struct {
	GroupName string
	Item      string
	CreatedAt time.Time
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) error {
	_, err := q.db.ExecContext(ctx, createJob, arg.GroupName, arg.Item, arg.CreatedAt)
	return err
}

const deleteJob = `-- name: DeleteJob :exec
DELETE FROM jobs_queue WHERE id = ?
`

func (q *Queries) DeleteJob(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteJob, id)
	return err
}

const getOldestJobByGroup = `-- name: GetOldestJobByGroup :one
SELECT id,item FROM jobs_queue 
WHERE group_name=?
ORDER BY created_at ASC
LIMIT 1
`

type GetOldestJobByGroupRow struct {
	ID   int64
	Item string
}

func (q *Queries) GetOldestJobByGroup(ctx context.Context, groupName string) (GetOldestJobByGroupRow, error) {
	row := q.db.QueryRowContext(ctx, getOldestJobByGroup, groupName)
	var i GetOldestJobByGroupRow
	err := row.Scan(&i.ID, &i.Item)
	return i, err
}
