// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"database/sql"
	"time"
)

type JobsQueue struct {
	ID        int64
	GroupName string
	Item      string
	CreatedAt time.Time
}

type User struct {
	ID             int64
	Name           string
	TelegramID     int64
	TelegramChatID int64
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type VocabWord struct {
	ID              int64
	PreplyID        sql.NullString
	Spelling        string
	Definition      string
	LexicalCategory string
	Lang            string
	TranslationRu   string
	AnsweredCount   int64
	ViewedCount     int64
	UserID          int64
	AddedAt         time.Time
	LearnedAt       sql.NullTime
	LastShowedAt    sql.NullTime
}

type VocabWordsExercise struct {
	ID                int64
	WordID            int64
	UserID            int64
	Question          string
	Answer            string
	TelegramMsgID     int64
	Answered          bool
	AnsweredCorrectly sql.NullBool
	CreatedAt         time.Time
	AnsweredAt        sql.NullTime
}
