// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package sqlc

import (
	"context"
	"time"
)

const createOrUpdateUser = `-- name: CreateOrUpdateUser :one
INSERT INTO users ( telegram_id, telegram_chat_id, name, created_at, updated_at ) VALUES (?, ?, ?, ?, ?)
ON CONFLICT (telegram_id, telegram_chat_id) DO UPDATE SET name=excluded.name, updated_at=excluded.updated_at
RETURNING id, name, telegram_id, telegram_chat_id, created_at, updated_at
`

type CreateOrUpdateUserParams struct {
	TelegramID     int64
	TelegramChatID int64
	Name           string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) CreateOrUpdateUser(ctx context.Context, arg CreateOrUpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createOrUpdateUser,
		arg.TelegramID,
		arg.TelegramChatID,
		arg.Name,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TelegramID,
		&i.TelegramChatID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByTelegramID = `-- name: GetUserByTelegramID :one
SELECT id, name, telegram_id, telegram_chat_id, created_at, updated_at FROM users WHERE telegram_id = ? AND telegram_chat_id = ?
`

type GetUserByTelegramIDParams struct {
	TelegramID     int64
	TelegramChatID int64
}

func (q *Queries) GetUserByTelegramID(ctx context.Context, arg GetUserByTelegramIDParams) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByTelegramID, arg.TelegramID, arg.TelegramChatID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TelegramID,
		&i.TelegramChatID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
