// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: vocab.sql

package sqlc

import (
	"context"
	"database/sql"
	"strings"
	"time"
)

const addWord = `-- name: AddWord :one
INSERT INTO vocab_words ( preply_id, spelling, definition, lexical_category, lang, translation_ru,  user_id, added_at, answered_count, viewed_count) VALUES (?, ?, ?, ?, ?, ?, ?, ?, 0, 0) RETURNING id, preply_id, spelling, definition, lexical_category, lang, translation_ru, answered_count, viewed_count, user_id, added_at, learned_at, last_showed_at
`

type AddWordParams struct {
	PreplyID        sql.NullString
	Spelling        string
	Definition      string
	LexicalCategory string
	Lang            string
	TranslationRu   string
	UserID          int64
	AddedAt         time.Time
}

func (q *Queries) AddWord(ctx context.Context, arg AddWordParams) (VocabWord, error) {
	row := q.db.QueryRowContext(ctx, addWord,
		arg.PreplyID,
		arg.Spelling,
		arg.Definition,
		arg.LexicalCategory,
		arg.Lang,
		arg.TranslationRu,
		arg.UserID,
		arg.AddedAt,
	)
	var i VocabWord
	err := row.Scan(
		&i.ID,
		&i.PreplyID,
		&i.Spelling,
		&i.Definition,
		&i.LexicalCategory,
		&i.Lang,
		&i.TranslationRu,
		&i.AnsweredCount,
		&i.ViewedCount,
		&i.UserID,
		&i.AddedAt,
		&i.LearnedAt,
		&i.LastShowedAt,
	)
	return i, err
}

const countLearningWords = `-- name: CountLearningWords :one
SELECT COUNT(*) FROM vocab_words WHERE user_id = ? AND viewed_count > 0 AND learned_at IS NULL
`

func (q *Queries) CountLearningWords(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLearningWords, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createExercise = `-- name: CreateExercise :one
;

INSERT INTO vocab_words_exercises (word_id, user_id, question, answer, telegram_msg_id, answered, created_at) 
VALUES(?,?,?,?,?,false,?) RETURNING id, word_id, user_id, question, answer, telegram_msg_id, answered, answered_correctly, created_at, answered_at
`

type CreateExerciseParams struct {
	WordID        int64
	UserID        int64
	Question      string
	Answer        string
	TelegramMsgID int64
	CreatedAt     time.Time
}

func (q *Queries) CreateExercise(ctx context.Context, arg CreateExerciseParams) (VocabWordsExercise, error) {
	row := q.db.QueryRowContext(ctx, createExercise,
		arg.WordID,
		arg.UserID,
		arg.Question,
		arg.Answer,
		arg.TelegramMsgID,
		arg.CreatedAt,
	)
	var i VocabWordsExercise
	err := row.Scan(
		&i.ID,
		&i.WordID,
		&i.UserID,
		&i.Question,
		&i.Answer,
		&i.TelegramMsgID,
		&i.Answered,
		&i.AnsweredCorrectly,
		&i.CreatedAt,
		&i.AnsweredAt,
	)
	return i, err
}

const getExerciseByTelegramIDAndUserID = `-- name: GetExerciseByTelegramIDAndUserID :one
SELECT id, word_id, user_id, question, answer, telegram_msg_id, answered, answered_correctly, created_at, answered_at FROM vocab_words_exercises WHERE user_id=? AND telegram_msg_id=?
`

type GetExerciseByTelegramIDAndUserIDParams struct {
	UserID        int64
	TelegramMsgID int64
}

func (q *Queries) GetExerciseByTelegramIDAndUserID(ctx context.Context, arg GetExerciseByTelegramIDAndUserIDParams) (VocabWordsExercise, error) {
	row := q.db.QueryRowContext(ctx, getExerciseByTelegramIDAndUserID, arg.UserID, arg.TelegramMsgID)
	var i VocabWordsExercise
	err := row.Scan(
		&i.ID,
		&i.WordID,
		&i.UserID,
		&i.Question,
		&i.Answer,
		&i.TelegramMsgID,
		&i.Answered,
		&i.AnsweredCorrectly,
		&i.CreatedAt,
		&i.AnsweredAt,
	)
	return i, err
}

const getLearningWord = `-- name: GetLearningWord :one
SELECT id, preply_id, spelling, definition, lexical_category, lang, translation_ru, answered_count, viewed_count, user_id, added_at, learned_at, last_showed_at FROM vocab_words WHERE user_id = ? AND viewed_count > 0 AND learned_at IS NULL ORDER BY last_showed_at ASC LIMIT 1
`

func (q *Queries) GetLearningWord(ctx context.Context, userID int64) (VocabWord, error) {
	row := q.db.QueryRowContext(ctx, getLearningWord, userID)
	var i VocabWord
	err := row.Scan(
		&i.ID,
		&i.PreplyID,
		&i.Spelling,
		&i.Definition,
		&i.LexicalCategory,
		&i.Lang,
		&i.TranslationRu,
		&i.AnsweredCount,
		&i.ViewedCount,
		&i.UserID,
		&i.AddedAt,
		&i.LearnedAt,
		&i.LastShowedAt,
	)
	return i, err
}

const getOldestUnseenWord = `-- name: GetOldestUnseenWord :one
SELECT id, preply_id, spelling, definition, lexical_category, lang, translation_ru, answered_count, viewed_count, user_id, added_at, learned_at, last_showed_at FROM vocab_words WHERE user_id = ? AND viewed_count = 0 ORDER BY added_at DESC LIMIT 1
`

func (q *Queries) GetOldestUnseenWord(ctx context.Context, userID int64) (VocabWord, error) {
	row := q.db.QueryRowContext(ctx, getOldestUnseenWord, userID)
	var i VocabWord
	err := row.Scan(
		&i.ID,
		&i.PreplyID,
		&i.Spelling,
		&i.Definition,
		&i.LexicalCategory,
		&i.Lang,
		&i.TranslationRu,
		&i.AnsweredCount,
		&i.ViewedCount,
		&i.UserID,
		&i.AddedAt,
		&i.LearnedAt,
		&i.LastShowedAt,
	)
	return i, err
}

const getUnansweredExerciseByUserID = `-- name: GetUnansweredExerciseByUserID :one
SELECT id, word_id, user_id, question, answer, telegram_msg_id, answered, answered_correctly, created_at, answered_at FROM vocab_words_exercises WHERE user_id=? AND answered=false ORDER BY telegram_msg_id ASC LIMIT 1
`

func (q *Queries) GetUnansweredExerciseByUserID(ctx context.Context, userID int64) (VocabWordsExercise, error) {
	row := q.db.QueryRowContext(ctx, getUnansweredExerciseByUserID, userID)
	var i VocabWordsExercise
	err := row.Scan(
		&i.ID,
		&i.WordID,
		&i.UserID,
		&i.Question,
		&i.Answer,
		&i.TelegramMsgID,
		&i.Answered,
		&i.AnsweredCorrectly,
		&i.CreatedAt,
		&i.AnsweredAt,
	)
	return i, err
}

const getWordByID = `-- name: GetWordByID :one
SELECT id, preply_id, spelling, definition, lexical_category, lang, translation_ru, answered_count, viewed_count, user_id, added_at, learned_at, last_showed_at FROM vocab_words WHERE id = ?
`

func (q *Queries) GetWordByID(ctx context.Context, id int64) (VocabWord, error) {
	row := q.db.QueryRowContext(ctx, getWordByID, id)
	var i VocabWord
	err := row.Scan(
		&i.ID,
		&i.PreplyID,
		&i.Spelling,
		&i.Definition,
		&i.LexicalCategory,
		&i.Lang,
		&i.TranslationRu,
		&i.AnsweredCount,
		&i.ViewedCount,
		&i.UserID,
		&i.AddedAt,
		&i.LearnedAt,
		&i.LastShowedAt,
	)
	return i, err
}

const incrementWordAnsweredCount = `-- name: IncrementWordAnsweredCount :one
UPDATE vocab_words SET answered_count = answered_count + 1 WHERE id = ? RETURNING answered_count
`

func (q *Queries) IncrementWordAnsweredCount(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, incrementWordAnsweredCount, id)
	var answered_count int64
	err := row.Scan(&answered_count)
	return answered_count, err
}

const incrementWordViewedCountByID = `-- name: IncrementWordViewedCountByID :exec
UPDATE vocab_words SET viewed_count = viewed_count + 1, last_showed_at = ? WHERE id = ?
`

type IncrementWordViewedCountByIDParams struct {
	LastShowedAt sql.NullTime
	ID           int64
}

func (q *Queries) IncrementWordViewedCountByID(ctx context.Context, arg IncrementWordViewedCountByIDParams) error {
	_, err := q.db.ExecContext(ctx, incrementWordViewedCountByID, arg.LastShowedAt, arg.ID)
	return err
}

const listExistingUserWordsByPreplyIDs = `-- name: ListExistingUserWordsByPreplyIDs :many
SELECT preply_id FROM vocab_words WHERE user_id = ? AND preply_id IN (/*SLICE:preplyIds*/?)
`

type ListExistingUserWordsByPreplyIDsParams struct {
	UserID    int64
	PreplyIds []sql.NullString
}

func (q *Queries) ListExistingUserWordsByPreplyIDs(ctx context.Context, arg ListExistingUserWordsByPreplyIDsParams) ([]sql.NullString, error) {
	query := listExistingUserWordsByPreplyIDs
	var queryParams []interface{}
	queryParams = append(queryParams, arg.UserID)
	if len(arg.PreplyIds) > 0 {
		for _, v := range arg.PreplyIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:preplyIds*/?", strings.Repeat(",?", len(arg.PreplyIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:preplyIds*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []sql.NullString
	for rows.Next() {
		var preply_id sql.NullString
		if err := rows.Scan(&preply_id); err != nil {
			return nil, err
		}
		items = append(items, preply_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetWordAnsweredCount = `-- name: ResetWordAnsweredCount :exec
UPDATE vocab_words SET answered_count = 0 WHERE id = ?
`

func (q *Queries) ResetWordAnsweredCount(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, resetWordAnsweredCount, id)
	return err
}

const setExerciseAnswer = `-- name: SetExerciseAnswer :one
;

UPDATE  vocab_words_exercises SET 
answered = ?,
answered_correctly= ?,
answered_at = ?
WHERE user_id = ? AND telegram_msg_id = ? RETURNING id, word_id, user_id, question, answer, telegram_msg_id, answered, answered_correctly, created_at, answered_at
`

type SetExerciseAnswerParams struct {
	Answered          bool
	AnsweredCorrectly sql.NullBool
	AnsweredAt        sql.NullTime
	UserID            int64
	TelegramMsgID     int64
}

func (q *Queries) SetExerciseAnswer(ctx context.Context, arg SetExerciseAnswerParams) (VocabWordsExercise, error) {
	row := q.db.QueryRowContext(ctx, setExerciseAnswer,
		arg.Answered,
		arg.AnsweredCorrectly,
		arg.AnsweredAt,
		arg.UserID,
		arg.TelegramMsgID,
	)
	var i VocabWordsExercise
	err := row.Scan(
		&i.ID,
		&i.WordID,
		&i.UserID,
		&i.Question,
		&i.Answer,
		&i.TelegramMsgID,
		&i.Answered,
		&i.AnsweredCorrectly,
		&i.CreatedAt,
		&i.AnsweredAt,
	)
	return i, err
}

const setWordLearned = `-- name: SetWordLearned :exec
UPDATE vocab_words SET learned_at = ? WHERE id = ?
`

type SetWordLearnedParams struct {
	LearnedAt sql.NullTime
	ID        int64
}

func (q *Queries) SetWordLearned(ctx context.Context, arg SetWordLearnedParams) error {
	_, err := q.db.ExecContext(ctx, setWordLearned, arg.LearnedAt, arg.ID)
	return err
}
